### ISSUE TITLE
Bot connection to lobby

### ISSUE THREAD

**Issue by oleghalin** [RJacksonm1/node-dota2#173] opened 2015-12-07 10:38 UTC
Hello, i have questions about this node, for example, can i create lobby by bot and set bot as spectetare. If can, how?

**Comment by jimmydorry** [comment] 2015-12-07 10:45
The functionality is there, from what I can see. Just a question of looking at the various examples and figuring out how to adapt them.

The only thing probably not working, is the setLobbyTeamSlot, which is waiting for someone that cares to test and implement.

https://github.com/RJacksonm1/node-dota2/blob/master/handlers/lobbies.js#L26

https://github.com/RJacksonm1/node-dota2/blob/master/handlers/lobbies.js#L67

https://github.com/RJacksonm1/node-dota2/blob/master/handlers/lobbies.js#L148

https://github.com/RJacksonm1/node-dota2/blob/master/handlers/lobbies.js#L148

https://github.com/RJacksonm1/node-dota2/blob/master/handlers/lobbies.js#L284

**Comment by jimmydorry** [comment] 2015-12-07 10:47
Oh, and you will want to be using dev.

https://github.com/RJacksonm1/node-dota2/tree/dev

Posted too soon, previously.

The functionality is there, from what I can see. Just a question of looking at the various examples and figuring out how to adapt them.

The only thing probably not working, is the setLobbyTeamSlot, which is waiting for someone that cares to test and implement.

https://github.com/RJacksonm1/node-dota2/blob/dev/handlers/lobbies.js#L33

https://github.com/RJacksonm1/node-dota2/blob/dev/handlers/lobbies.js#L75

https://github.com/RJacksonm1/node-dota2/blob/dev/handlers/lobbies.js#L158

https://github.com/RJacksonm1/node-dota2/blob/dev/handlers/lobbies.js#L201

https://github.com/RJacksonm1/node-dota2/blob/dev/handlers/lobbies.js#L299

https://github.com/RJacksonm1/node-dota2/blob/dev/handlers/lobbies.js#L321

https://github.com/RJacksonm1/node-dota2/blob/dev/handlers/lobbies.js#L348

**Comment by oleghalin** [comment] 2015-12-07 10:54
When you will finsih setLobbyTeamSlot? Its will be need me to teams generating

**Comment by jimmydorry** [comment] 2015-12-07 11:02
You should play around with it. You are likely not going to get far in making anything, without some critical thinking.

Have a read of this thread. Some of the way down it, I shared a compiled version the tools commonly used to figure out what exactly the client is doing.

https://github.com/RJacksonm1/node-dota2/issues/141

When you get stuck, come and open a thread specific to the issue you are encountering... **and make sure to read all of the readme in the DEV branch (linked above)**

**Comment by Crazy-Duck** [comment] 2015-12-07 11:05
This CMsg has been implemented in the mean time. It was split in a function for adding bots and one for setting player team. See joinPracticeLobbyTeam and addBotToPracticeLobby

**Comment by oleghalin** [comment] 2015-12-07 13:39
![image](https://cloud.githubusercontent.com/assets/9086983/11628175/935bb156-9cf8-11e5-8ed8-a13f657b7bc8.png)
Okay. Thank you, when i trying to set game mode or game name like this one, i have empty game mode and game name, what i doing wrong? (In the screen i setting just game_mode)

**Comment by Crazy-Duck** [comment] 2015-12-07 13:59
As far as I can see you're calling the function with the correct parameters. Does the data in the callback look something like `{result: 1}` ? If not, can you provide a little more context? Like how did you define `Dota2`, did you already establish a connection with Steam/the GC...?

**Comment by oleghalin** [comment] 2015-12-07 14:00
![image](https://cloud.githubusercontent.com/assets/9086983/11628620/8ad1f7e0-9cfb-11e5-8d17-871cd599fa94.png)
Im not good in Eng, but i tried to understand all of your words))

**Comment by jimmydorry** [comment] 2015-12-07 14:09
A result of 2 is "fail" in Steam's enums.

**Comment by oleghalin** [comment] 2015-12-07 14:14
Okay, thank you, ill check. 

And can i ask question about function of bot? Can this bot after start game get info about this game? For example just a id of match

**Comment by Crazy-Duck** [comment] 2015-12-07 14:50
The bot can basically do anything you can do with the regular Reborn client. As for your example, can you post the entire argument set you're using?
No sweat about the english, you're doing fine :smile:

**Comment by oleghalin** [comment] 2015-12-07 15:05
"you post the entire argument set you're using?" What you mean? 

And after "npm install steam" i have an error with load
![image](https://cloud.githubusercontent.com/assets/9086983/11630120/b061fb3c-9d04-11e5-8984-364c1580d0d3.png)

**Comment by oleghalin** [comment] 2015-12-07 15:51
Fixed :)

**Comment by Crazy-Duck** [comment] 2015-12-08 09:02
If the issue is resolved, can you close it?

**Comment by oleghalin** [comment] 2015-12-08 09:03
Crazy, i have some question about it and maybe pay job if your interest ofc

**Comment by jimmydorry** [comment] 2015-12-08 09:32
You can continue commenting on a closed issue, but I highly recommend trying your own hand at it and opening a new issue when you have a specific problem.

**Closed by jimmydorry** 2015-12-08 09:32 UTC
Labels: help me
